CREATE DATABASE UserRoleDB;
GO

USE UserRoleDB;
GO

CREATE TABLE Roles (
    id INT IDENTITY(1,1) PRIMARY KEY,
    name NVARCHAR(100) NOT NULL UNIQUE,
    description NVARCHAR(255) NOT NULL DEFAULT '',
    isDeleted BIT NOT NULL DEFAULT 0,
    createdAt DATETIME2 NOT NULL DEFAULT GETDATE(),
    updatedAt DATETIME2 NOT NULL DEFAULT GETDATE()
);
GO

CREATE TABLE Users (
    id INT IDENTITY(1,1) PRIMARY KEY,
    username NVARCHAR(100) NOT NULL UNIQUE,
    password NVARCHAR(255) NOT NULL,
    email NVARCHAR(150) NOT NULL UNIQUE,
    fullName NVARCHAR(150) NOT NULL DEFAULT '',
    avatarUrl NVARCHAR(500) NOT NULL DEFAULT 'https://i.sstatic.net/l60Hf.png',
    status BIT NOT NULL DEFAULT 0,
    roleId INT NULL,
    loginCount INT NOT NULL DEFAULT 0 CHECK (loginCount >= 0),
    isDeleted BIT NOT NULL DEFAULT 0,
    createdAt DATETIME2 NOT NULL DEFAULT GETDATE(),
    updatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_Users_Roles FOREIGN KEY (roleId) REFERENCES Roles(id)
);
GO